services:
  -postgres:
    container_name: postgres
    image: postgres:18
    environment:
      POSTGRES_DB: sge
      POSTGRES_USER: sge
      POSTGRES_PASSWORD: sge
    volumes:
      - postgres:/var/lib/postgresql/18/docker
    ports:
      - 5434:5432

volumes:
  postgres:
